### ISSUE TITLE
issue with blender exportation for import in vicardia

### ISSUE THREAD

**Issue by johnfelipe** [Misterblue/convoar#11]
im use your convoar latest version
import with model viewer of google https://modelviewer.dev/editor/
download scene
import in blender

https://discord.com/channels/564926326025224212/656044316128575488/979455690437443635

i put all model in ground

export to gltf
import to vicardia

but somethin happend with scale 
https://cdn.discordapp.com/attachments/656044316128575488/979456403892744232/SNAG-1037.png

how solve this?

**Comment by Misterblue** [comment]
I see  that you were talking to the Vircadia people. Do you have the scale thing resolved?

At the moment, Convoar doesn't do anything with scale -- everything is scaled as 1. If there was any scaling specified in the prims, the mesh is scaled up.

**Comment by johnfelipe** [comment]
Can u solve that scale issue, because is something bad, how can help u, i
send you 2 OAR, for review error, but use it if u can for solve scale
problem

**Comment by Misterblue** [comment]
I believe I've added you as a friend on Discord. We can talk there.

**Comment by johnfelipe** [comment]
ok chat with me there pls
