### ISSUE TITLE
how export convoar folder with all contents to gltf

### ISSUE THREAD

**Issue by johnfelipe** [Misterblue/convoar#12]
im use your convoar latest version
import with model viewer of google https://modelviewer.dev/editor/ 
download scene

but can u tell me if another options?

**Comment by Misterblue** [comment]
Other options for what? Viewing? Editing? Converting?

**Comment by johnfelipe** [comment]
Editing

**Comment by Misterblue** [comment]
Convoar does OAR to mesh conversion. It doesn't provide options for editing. There are some optimization functions (with more to come) but, for editing, you will need to rely on Blender or any of  the other mesh/scene editing tools.
If there are any problems with the generated GLTF files that don't allow editing in those tools, you should file an issue.

**Comment by johnfelipe** [comment]
ok
tnks
close this issue
