### ISSUE TITLE
Command line parameters

### ISSUE THREAD

**Issue by lazydino** [Misterblue/convoar#3]
Hi,

What is the correct way to specify output dir? With the current codebase, I run convoar.exe under dist directory in Windows 10, it seems produce the output in dist sub directoy when I specify "--OutputDir myoutputdir" or "-d  myoutputdit" as parameters.

**Comment by Misterblue** [comment]
I will add some documentation. Specifying output directory can be done with both "-d" and "--outputdir".

"convoar --help" will list all the possible parameters.
