### ISSUE TITLE
GLTF not loading in other viewers, missing images/

### ISSUE THREAD

**Issue by riebling** [Misterblue/convoar#4]
I was thrilled to discover the converted OAR samples page, and tried several, but now after coming here, realize that the downloads seem to be missing the images/ content.

Another thing I'd like to try next is running the results through a GLTF checker. I tried loading some into A-Frame (another convenient tool for displaying GLTF models and more on just about any device, in a web page) and got failures on all the ones tried, but need the checker output to learn exactly what failed.

It was also great to see the information here, I didn't know about the .buf files, and how they relate to the .gltf file.

This saves SO MUCH EFFORT versus my current shoddy path using an ancient OpenSim OAR to Unity project importer, then exporting THAT to a similarly ancient Unity to A-Frame exporter, the end goal being to be able to view our glorious OpenSim builds in A-Frame, which nicely wraps three.js into simple, delcarative HTML (and runs everywhere, as mentioned)

Good luck, thanks so much, maybe I'll dig deeper with time and contribute any learnings & fixes!

**Comment by riebling** [comment]
AHA! Working much better now that I learned a few things:
  * the ZIP files in https://misterblue.com/oars/ tend to be missing the bitmaps
  * the tarballs tend to have them :)
  * bitmaps reside in same folder as .gltf (not a folder named images/ or models/)
Awesome!

**Comment by Misterblue** [comment]
I fixed a problem where, if images couldn't be found in the OAR, the output GLTF would still reference the non-existent image.  It now replaces the missing image with a temp image and the GLTF loads much better.
